### PR TITLE
feat: remove unnecessary body and content-length processing

### PR DESCRIPTION
**Pull request by mredele**

### CODE REVIEW

**Comment by mredele** [comment]
It's a breaking change so bumped major version. 
The functional change is in the first commit.

**Review by sravan-archilogic — APPROVED** [review]
LGTM!

**Review by kialysa — COMMENTED** [review]
~~when installing commit https://github.com/archilogic-com/lambda-expressless/pull/11/commits/9c4cc95a2cff7ed6cbefcd57c9d419039f797984 in microservices and running the tests, I get one or two failures which don't fail in master.. 🤔 Or is it just me....~~

Ah you wrote they are breaking changes so i guess we just haven't updated microservices repo yet to accommodate those changes?

**Comment by mredele** [comment]
@kialysa exactly, it needs microservices changes

**Review by kialysa — APPROVED** [review]

**Pull request merged**
